#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_MED_ASN_Kumiko_Head_01_Dyn_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass F_MED_ASN_Kumiko_Head_01_Dyn_AnimBP.F_MED_ASN_Kumiko_Head_01_Dyn_AnimBP_C
// 0x00B8 (0x04E8 - 0x0430)
class UF_MED_ASN_Kumiko_Head_01_Dyn_AnimBP_C final  : public UCustomCharacterPartAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0430(0x0008)(Transient, DuplicateTransient)
	struct FAnimNode_SubInput                     AnimGraphNode_SubInput_0F0146F2436CE633517C27B19B488966; // 0x0438(0x0068)()
	struct FAnimNode_Root                         AnimGraphNode_Root_FDEA838F43F99118C8776885E17D1C7F; // 0x04A0(0x0048)()

public:
	void ExecuteUbergraph_F_MED_ASN_Kumiko_Head_01_Dyn_AnimBP(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_MED_ASN_Kumiko_Head_01_Dyn_AnimBP_C">();
	}
	static class UF_MED_ASN_Kumiko_Head_01_Dyn_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_MED_ASN_Kumiko_Head_01_Dyn_AnimBP_C>();
	}
};

}

