#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_RiftZapPlayer

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_RiftZapPlayer.GCN_RiftZapPlayer_C
// 0x0000 (0x00B0 - 0x00B0)
class UGCN_RiftZapPlayer_C final  : public UFortGameplayCueNotify_Simple
{
public:
	bool OnExecute(class AActor* MyTarget, struct FGameplayCueParameters& Parameters, const struct FTransform& CallFunc_MakeTransform_ReturnValue, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class AActor* CallFunc_EffectContextGetEffectCauser_ReturnValue, class AB_DtB_LightningZap_C* CallFunc_FinishSpawningActor_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, bool CallFunc_OnExecute_ReturnValue, class APlayerPawn_Generic_C* K2Node_DynamicCast_AsPlayer_Pawn_Generic, bool K2Node_DynamicCast_bSuccess, class AB_DtB_LightningZap_C* K2Node_DynamicCast_AsB_Dt_B_Lightning_Zap, bool K2Node_DynamicCast_bSuccess1) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_RiftZapPlayer_C">();
	}
	static class UGCN_RiftZapPlayer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_RiftZapPlayer_C>();
	}
};

}

