#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemManagementMulchModeBox

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ItemManagementMulchModeBox.ItemManagementMulchModeBox_C
// 0x0010 (0x0420 - 0x0410)
class UItemManagementMulchModeBox_C final  : public UFortItemMulchModeActivatablePanel
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0410(0x0008)(Transient, DuplicateTransient)
	class UItemWindow_C*                          Recycle_Info_Window;                               // 0x0418(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ItemManagementMulchModeBox(int32 EntryPoint, const struct FDataTableRowHandle& K2Node_MakeStruct_DataTableRowHandle, TDelegate<void(bool* bPassThrough)> K2Node_CreateDelegate_OutputDelegate, class UItemWindow_C* CallFunc_Create_ReturnValue, class UItemManagementMulchDetailsPanel_C* K2Node_DynamicCast_AsItem_Management_Mulch_Details_Panel, bool K2Node_DynamicCast_bSuccess, TDelegate<void(bool* bPassThrough)> K2Node_CreateDelegate_OutputDelegate1, class UItemManagementMulchDetailsPanel_C* K2Node_DynamicCast_AsItem_Management_Mulch_Details_Panel1, bool K2Node_DynamicCast_bSuccess1, TDelegate<void()> K2Node_CreateDelegate_OutputDelegate12, class UFortUINavigationManager* CallFunc_GetUINavigationManager_ReturnValue, const struct FDataTableRowHandle& K2Node_MakeStruct_DataTableRowHandle1, TDelegate<void(bool* bPassThrough)> K2Node_CreateDelegate_OutputDelegate123, class UFortHUDContext* CallFunc_GetContext_ReturnValue, class UFortGlobalUIContext* CallFunc_GetContext_ReturnValue1, TDelegate<void(bool bCursorModeEnabled)> K2Node_CreateDelegate_OutputDelegate1234, bool CallFunc_IsInZone_ReturnValue);
	void Destruct();
	void OnActivated();
	void Construct();
	void HandleDifferentItemToDetailSetBP();
	void HandleBack(bool* Passthrough);
	void HandleInfo(bool* Pass_Through, class FText CallFunc_MakeLiteralText_ReturnValue, TArray<class UFortItemDefinition*>& CallFunc_GetItemDefinitions_ReturnValue, class UFortUIManagerWidget_NUI* CallFunc_GetUIManagerWidget_ReturnValue);
	void HandleMulchListChanged(bool Temp_bool_Variable, EInputActionState Temp_byte_Variable, EInputActionState Temp_byte_Variable1, TArray<class UFortItem*>& CallFunc_GetItemsToMulch_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, EInputActionState K2Node_Select_Default);
	void HandleCursorModeChanging(bool IsEnabled, bool CallFunc_HandleBack_PassThrough, bool CallFunc_Not_PreBool_ReturnValue);
	void HandleLeaveInventory(bool* Passthrough, class UFortHUDContext* CallFunc_GetContext_ReturnValue);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ItemManagementMulchModeBox_C">();
	}
	static class UItemManagementMulchModeBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemManagementMulchModeBox_C>();
	}
};

}

